files:
  - source: /src/emu/qt/translations/eka2l1.ts
    translation: /src/emu/qt/translations/eka2l1_%locale_with_underscore%.ts
  - source: /src/emu/android/app/src/main/res/values/strings.xml
    translation: /src/emu/android/app/src/main/res/values-%android_code%/%original_file_name%
    languages_mapping:
      android_code:
        af: af
        ar: ar
        az: az
        bg: bg
        be: be
        bn: bn
        ca: ca
        cs: cs
        da: da
        nl: nl
        fi: fi
        fil: fil
        fr: fr
        de: de
        el: el
        fa: fa
        he: iw
        hu: hu
        id: in
        it: it
        ja: ja
        ko: ko
        ms: ms
        no: no
        pl: pl
        pt-PT: pt
        ro: ro
        ru: ru
        si-LK: si
        sr: sr
        es-ES: es
        sv-SE: sv
        th: th
        tr: tr
        uk: uk
        vi: vi
