/*
 * Copyright (c) 2021 EKA2L1 Team.
 * 
 * This file is part of EKA2L1 project
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef KEY_CODE
#define KEY_CODE(name, nice_name, code)
#endif

KEY_CODE(KEY_TAB, "Tab", 258)
KEY_CODE(KEY_BACKSPACE, "Backspace", 259)
KEY_CODE(KEY_LEFT_SHIFT, "Left Shift", 340)
KEY_CODE(KEY_LEFT_CONTROL, "Left control", 341)
KEY_CODE(KEY_LEFT_ALT, "Left Alt", 342)
KEY_CODE(KEY_LEFT_SUPER, "Left Super", 343)
KEY_CODE(KEY_RIGHT_SHIFT, "Right Shift", 344)
KEY_CODE(KEY_RIGHT_CONTROL, "Right control", 345)
KEY_CODE(KEY_RIGHT_ALT, "Right Alt", 346)
KEY_CODE(KEY_RIGHT_SUPER, "Right Super", 347)

KEY_CODE(KEY_RIGHT, "Right arrow", 262)
KEY_CODE(KEY_LEFT, "Left arrow", 263)
KEY_CODE(KEY_DOWN, "Down arrow", 264)
KEY_CODE(KEY_UP, "Up arrow", 265)

KEY_CODE(KEY_ENTER, "Enter", 257)
KEY_CODE(KEY_ESCAPE, "Esc", 256)

KEY_CODE(KEY_NUM0, "Numpad 0", 320)
KEY_CODE(KEY_NUM1, "Numpad 1", 321)
KEY_CODE(KEY_NUM2, "Numpad 2", 322)
KEY_CODE(KEY_NUM3, "Numpad 3", 323)
KEY_CODE(KEY_NUM4, "Numpad 4", 324)
KEY_CODE(KEY_NUM5, "Numpad 5", 325)
KEY_CODE(KEY_NUM6, "Numpad 6", 326)
KEY_CODE(KEY_NUM7, "Numpad 7", 327)
KEY_CODE(KEY_NUM8, "Numpad 8", 328)
KEY_CODE(KEY_NUM9, "Numpad 9", 329)
KEY_CODE(KEY_SLASH, "Slash", 331)
KEY_CODE(KEY_STAR, "Star", 332)

KEY_CODE(KEY_F1, "F1", 290)
KEY_CODE(KEY_F2, "F2", 291)
KEY_CODE(KEY_F11, "F11", 300)

KEY_CODE(KEY_A, "A", 65)
KEY_CODE(KEY_B, "B", 66)
KEY_CODE(KEY_C, "C", 67)
KEY_CODE(KEY_D, "D", 68)
KEY_CODE(KEY_E, "E", 69)
KEY_CODE(KEY_F, "F", 70)
KEY_CODE(KEY_G, "G", 71)
KEY_CODE(KEY_H, "H", 72)
KEY_CODE(KEY_I, "I", 73)
KEY_CODE(KEY_J, "J", 74)
KEY_CODE(KEY_K, "K", 75)
KEY_CODE(KEY_L, "L", 76)
KEY_CODE(KEY_M, "M", 77)
KEY_CODE(KEY_N, "N", 78)
KEY_CODE(KEY_O, "O", 79)
KEY_CODE(KEY_P, "P", 80)
KEY_CODE(KEY_Q, "Q", 81)
KEY_CODE(KEY_R, "R", 82)
KEY_CODE(KEY_S, "S", 83)
KEY_CODE(KEY_T, "T", 84)
KEY_CODE(KEY_U, "U", 85)
KEY_CODE(KEY_V, "V", 86)
KEY_CODE(KEY_W, "W", 87)
KEY_CODE(KEY_X, "X", 88)
KEY_CODE(KEY_Y, "Y", 89)
KEY_CODE(KEY_Z, "Z", 90)