#include <cstdint>

namespace eka2l1::epoc::bt {
    enum query_opcode : std::uint8_t {
        QUERY_OPCODE_GET_NAME,
        QUERY_OPCODE_GET_VIRTUAL_BLUETOOTH_ADDRESS,
        QUERY_OPCODE_IS_REAL_PORT_MAPPED_TO_VIRTUAL_PORT,
        QUERY_OPCODE_GET_REAL_PORT_FROM_VIRTUAL_PORT,
        QUERY_OPCODE_GET_PLAYERS,
        QUERY_OPCODE_NOTIFY_PLAYER_EXISTENCE,
        QUERY_OPCODE_ALLOW_MATCHING,
        QUERY_OPCODE_MATCHING_CONFIRMED,
        QUERY_OPCODE_MATCHING_DENIED,

        QUERY_OPCODE_SERVER_LOGIN,
        QUERY_OPCODE_SERVER_LOGOUT,
        QUERY_OPCODE_RESULT_START = 100
    };
}