/*
 * Copyright (c) 2018 EKA2L1 Team.
 *
 * This file is part of EKA2L1 project
 * (see bentokun.github.com/EKA2L1).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
#include <common/language.h>
#include <map>

static std::map<int, std::string> lang_map {
    { 0, "ELangTest" },
	{ 1, "ELangEnglish" },
	{ 2, "ELangFrench" },
	{ 3, "ELangGerman" },
	{ 4, "ELangSpanish" },
	{ 5, "ELangItalian" },
	{ 6, "ELangSwedish" },
	{ 7, "ELangDanish" },
	{ 8, "ELangNorwegian" },
	{ 9, "ELangFinnish" },
	{ 10, "ELangAmerican" },
	{ 11, "ELangSwissFrench" },
	{ 12, "ELangSwissGerman" },
	{ 13, "ELangPortuguese" },
	{ 14, "ELangTurkish" },
	{ 15, "ELangIcelandic" },
	{ 16, "ELangRussian" },
	{ 17, "ELangHungarian" },
	{ 18, "ELangDutch" },
	{ 19, "ELangBelgianFlemish" },
	{ 20, "ELangAustralian" },
	{ 21, "ELangBelgianFrench" },
	{ 22, "ELangAustrian" },
	{ 23, "ELangNewZealand" },
	{ 24, "ELangInternationalFrench" },
	{ 25, "ELangCzech" },
	{ 26, "ELangSlovak" },
	{ 27, "ELangPolish" },
	{ 28, "ELangSlovenian" },
	{ 29, "ELangTaiwanChinese" },
	{ 30, "ELangHongKongChinese" },
	{ 31, "ELangPrcChinese" },
	{ 32, "ELangJapanese" },
	{ 33, "ELangThai" },
	{ 34, "ELangAfrikaans" },
	{ 35, "ELangAlbanian" },
	{ 36, "ELangAmharic" },
	{ 37, "ELangArabic" },
	{ 38, "ELangArmenian" },
	{ 39, "ELangTagalog" },
	{ 40, "ELangBelarussian" },
	{ 41, "ELangBengali" },
	{ 42, "ELangBulgarian" },
	{ 43, "ELangBurmese" },
	{ 44, "ELangCatalan" },
	{ 45, "ELangCroatian" },
	{ 46, "ELangCanadianEnglish" },
	{ 47, "ELangInternationalEnglish" },
	{ 48, "ELangSouthAfricanEnglish" },
	{ 49, "ELangEstonian" },
	{ 50, "ELangFarsi" },
	{ 51, "ELangCanadianFrench" },
	{ 52, "ELangScotsGaelic" },
	{ 53, "ELangGeorgian" },
	{ 54, "ELangGreek" },
	{ 55, "ELangCyprusGreek" },
	{ 56, "ELangGujarati" },
	{ 57, "ELangHebrew" },
	{ 58, "ELangHindi" },
	{ 59, "ELangIndonesian" },
	{ 60, "ELangIrish" },
	{ 61, "ELangSwissItalian" },
	{ 62, "ELangKannada" },
	{ 63, "ELangKazakh" },
	{ 64, "ELangKhmer" },
	{ 65, "ELangKorean" },
	{ 66, "ELangLao" },
	{ 67, "ELangLatvian" },
	{ 68, "ELangLithuanian" },
	{ 69, "ELangMacedonian" },
	{ 70, "ELangMalay" },
	{ 71, "ELangMalayalam" },
	{ 72, "ELangMarathi" },
	{ 73, "ELangMoldavian" },
	{ 74, "ELangMongolian" },
	{ 75, "ELangNorwegianNynorsk" },
	{ 76, "ELangBrazilianPortuguese" },
	{ 77, "ELangPunjabi" },
	{ 78, "ELangRomanian" },
	{ 79, "ELangSerbian" },
	{ 80, "ELangSinhalese" },
	{ 81, "ELangSomali" },
	{ 82, "ELangInternationalSpanish" },
	{ 83, "ELangLatinAmericanSpanish" },
	{ 84, "ELangSwahili" },
	{ 85, "ELangFinlandSwedish" },
	{ 86, "ELangReserved1" },
	{ 87, "ELangTamil" },
	{ 88, "ELangTelugu" },
	{ 89, "ELangTibetan" },
	{ 90, "ELangTigrinya" },
	{ 91, "ELangCyprusTurkish" },
	{ 92, "ELangTurkmen" },
	{ 93, "ELangUkrainian" },
	{ 94, "ELangUrdu" },
	{ 95, "ELangReserved2" },
	{ 96, "ELangVietnamese" },
	{ 97, "ELangWelsh" },
	{ 98, "ELangZulu" },
	{ 99, "ELangOther" },
	{ 100, "ELangManufacturerEnglish" },
	{ 101, "ELangSouthSotho" },
	{ 102, "ELangBasque" },
	{ 103, "ELangGalician" },
	{ 104, "ELangJavanese" },
	{ 105, "ELangMaithili" },
	{ 106, "ELangAzerbaijani_Latin" },
	{ 107, "ELangAzerbaijani_Cyrillic" },
	{ 108, "ELangOriya" },
	{ 109, "ELangBhojpuri" },
	{ 110, "ELangSundanese" },
	{ 111, "ELangKurdish_Latin" },
	{ 112, "ELangKurdish_Arabic" },
	{ 113, "ELangPashto" },
	{ 114, "ELangHausa" },
	{ 115, "ELangOromo" },
	{ 116, "ELangUzbek_Latin" },
	{ 117, "ELangUzbek_Cyrillic" },
	{ 118, "ELangSindhi_Arabic" },
	{ 119, "ELangSindhi_Devanagari" },
	{ 120, "ELangYoruba" },
	{ 121, "ELangCebuano" },
	{ 122, "ELangIgbo" },
	{ 123, "ELangMalagasy" },
	{ 124, "ELangNepali" },
	{ 125, "ELangAssamese" },
	{ 126, "ELangShona" },
	{ 127, "ELangZhuang" },
	{ 128, "ELangMadurese" },
	{ 129, "ELangEnglish_Apac" },
	{ 157, "ELangEnglish_Taiwan" },
	{ 158, "ELangEnglish_HongKong" },
	{ 159, "ELangEnglish_Prc" },
	{ 160, "ELangEnglish_Japan" },
	{ 161, "ELangEnglish_Thailand" },
	{ 162, "ELangFulfulde" },
	{ 163, "ELangTamazight" },
	{ 164, "ELangBolivianQuechua" },
	{ 165, "ELangPeruQuechua" },
	{ 166, "ELangEcuadorQuechua" },
	{ 167, "ELangTajik_Cyrillic" },
	{ 168, "ELangTajik_PersoArabic" },
	{ 169, "ELangNyanja" },
	{ 170, "ELangHaitianCreole" },
	{ 171, "ELangLombard" },
	{ 172, "ELangKoongo" },
	{ 173, "ELangAkan" },
	{ 174, "ELangHmong" },
	{ 175, "ELangYi" },
	{ 176, "ELangTshiluba" },
	{ 177, "ELangIlocano" },
	{ 178, "ELangUyghur" },
	{ 179, "ELangNeapolitan" },
	{ 180, "ELangRwanda" },
	{ 181, "ELangXhosa" },
	{ 182, "ELangBalochi" },
	{ 183, "ElangHiligaynon" },
	{ 184, "ELangMinangkabau" },
	{ 185, "ELangMakhuwa" },
	{ 186, "ELangSantali" },
	{ 187, "ELangGikuyu" },
	{ 188, "ELangMoore" },
	{ 189, "ELangGuarani" },
	{ 190, "ELangRundi" },
	{ 191, "ELangRomani_Latin" },
	{ 192, "ELangRomani_Cyrillic" },
	{ 193, "ELangTswana" },
	{ 194, "ELangKanuri" },
	{ 195, "ELangKashmiri_Devanagari" },
	{ 196, "ELangKashmiri_PersoArabic" },
	{ 197, "ELangUmbundu" },
	{ 198, "ELangKonkani" },
	{ 199, "ELangBalinese" },
	{ 200, "ELangNorthernSotho" },
	{ 201, "ELangWolof" },
	{ 202, "ELangBemba" },
	{ 203, "ELangTsonga" },
	{ 204, "ELangYiddish" },
	{ 205, "ELangKirghiz" },
	{ 206, "ELangGanda" },
	{ 207, "ELangSoga" },
	{ 208, "ELangMbundu" },
	{ 209, "ELangBambara" },
	{ 210, "ELangCentralAymara" },
	{ 211, "ELangZarma" },
	{ 212, "ELangLingala" },
	{ 213, "ELangBashkir" },
	{ 214, "ELangChuvash" },
	{ 215, "ELangSwati" },
	{ 216, "ELangTatar" },
	{ 217, "ELangSouthernNdebele" },
	{ 218, "ELangSardinian" },
	{ 219, "ELangScots" },
	{ 220, "ELangMeitei" },
	{ 221, "ELangWalloon" },
	{ 222, "ELangKabardian" },
	{ 223, "ELangMazanderani" },
	{ 224, "ELangGilaki" },
	{ 225, "ELangShan" },
	{ 226, "ELangLuyia" },
	{ 227, "ELanguageLuo" },
	{ 228, "ELangSukuma" },
	{ 229, "ELangAceh" },
    { 230, "ELangEnglish_India" },
	{ 326, "ELangMalay_Apac" },
	{ 327, "ELangIndonesian_Apac" },
	{ 0xFFFF, "ELangNone" }
};

namespace eka2l1::common {
    std::string get_language_name_by_code(int lang_code) {
        if (lang_map.count(lang_code) == 1)
            return lang_map.at(lang_code);
        return "Language not found";
    }
}
